language: c
sudo: required
services:
  - docker
env:
  - OS=ubuntu-16.04
  - OS=fedora-25
  - OS=opensuse-leap
install:
  - sudo apt-get update && sudo apt-get -y install docker-ce
  - sudo docker pull "cangjians/pycangjie:${OS}"
  - sudo docker tag "cangjians/pycangjie:${OS}" "cangjians/pycangjie:latest"
  - sudo docker build --build-arg OS=${OS} -t "cangjians/ibus-cangjie:${OS}" .
script:
  - sudo docker run -it --rm "cangjians/ibus-cangjie:${OS}" make distcheck
